/**
 * MSG91 — SMS OTP + WhatsApp messaging
 * (Vercel serverless version — mirrors /backend/lib/msg91.js)
 *
 * Env vars required:
 *   MSG91_AUTH_KEY                  — MSG91 auth key
 *   MSG91_OTP_TEMPLATE_ID           — SMS OTP template ID (from MSG91 panel)
 *   MSG91_WA_NUMBER                 — Integrated WhatsApp business number (91XXXXXXXXXX)
 *   MSG91_WA_CREDENTIALS_TEMPLATE   — WhatsApp template name for welcome/credentials
 *   MSG91_WA_CREDENTIALS_SID        — Content SID for credentials template
 *   MSG91_WA_DONATION_TEMPLATE      — WhatsApp template name for donation confirmation
 *   MSG91_WA_DONATION_SID           — Content SID for donation template
 *
 * WhatsApp Template vars:
 *   Credentials: {{1}}=name, {{2}}=userId, {{3}}=password, {{4}}=loginUrl
 *   Donation:    {{1}}=name, {{2}}=amount, {{3}}=donationId, {{4}}=paymentId, {{5}}=date
 */

const BASE_OTP = 'https://control.msg91.com/api/v5/otp';
const BASE_WA  = 'https://api.msg91.com/api/v5/whatsapp/whatsapp-outbound-message/bulk/';

const authKey  = () => process.env.MSG91_AUTH_KEY || '';
const waNumber = () => process.env.MSG91_WA_NUMBER || '';

/** Format mobile to India format: 91XXXXXXXXXX */
function fmtMobile(mobile) {
  const digits = String(mobile).replace(/\D/g, '');
  return digits.startsWith('91') && digits.length === 12 ? digits : `91${digits.slice(-10)}`;
}

// ─── SMS OTP ─────────────────────────────────────────────────────────────────

/**
 * Send OTP via MSG91 SMS.
 * OTP must be generated by caller; MSG91 will inject it into the approved template.
 */
export async function sendSmsOtp({ mobile, otp }) {
  const key        = authKey();
  const templateId = process.env.MSG91_OTP_TEMPLATE_ID;
  if (!key || !templateId) {
    console.warn('⚠️ MSG91 SMS OTP skipped — MSG91_AUTH_KEY or MSG91_OTP_TEMPLATE_ID not set');
    return null;
  }

  try {
    const res = await fetch(BASE_OTP, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'Authkey': key },
      body:    JSON.stringify({ template_id: templateId, mobile: fmtMobile(mobile), otp: String(otp) })
    });
    const data = await res.json();
    if (data.type === 'success') console.log(`✅ MSG91 SMS OTP sent → ${mobile}`);
    else console.error('⚠️ MSG91 SMS OTP error:', JSON.stringify(data));
    return data;
  } catch (e) {
    console.error('⚠️ MSG91 SMS OTP failed:', e.message);
    return null;
  }
}

// ─── WhatsApp ─────────────────────────────────────────────────────────────────

/** Internal: send a WhatsApp template message via MSG91 */
async function _sendWhatsApp({ mobile, templateName, contentSid, variables = [] }) {
  const key  = authKey();
  const from = waNumber();
  if (!key || !from) {
    console.warn('⚠️ MSG91 WhatsApp skipped — MSG91_AUTH_KEY or MSG91_WA_NUMBER not set');
    return null;
  }

  const components = variables.length
    ? [{ type: 'body', parameters: variables.map(v => ({ type: 'text', text: String(v) })) }]
    : [];

  const body = {
    integrated_number: from,
    content_sid:       contentSid || '',
    payload: {
      messaging_product: 'whatsapp',
      type:     'template',
      to:       fmtMobile(mobile),
      template: {
        name:       templateName,
        language:   { code: 'en' },
        components
      }
    }
  };

  try {
    const res  = await fetch(BASE_WA, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'Authkey': key },
      body:    JSON.stringify(body)
    });
    const data = await res.json();
    const ok = data.type === 'success' || String(data.message || '').toLowerCase().includes('success');
    if (ok) console.log(`✅ MSG91 WhatsApp [${templateName}] sent → ${mobile}`);
    else    console.error(`⚠️ MSG91 WhatsApp [${templateName}] error:`, JSON.stringify(data));
    return data;
  } catch (e) {
    console.error(`⚠️ MSG91 WhatsApp [${templateName}] failed:`, e.message);
    return null;
  }
}

/**
 * Send welcome WhatsApp with login credentials.
 * Template vars: {{1}}=name  {{2}}=userId  {{3}}=password  {{4}}=loginUrl
 */
export async function sendWhatsAppCredentials({ mobile, name, userId, password }) {
  if (!mobile) return null;
  return _sendWhatsApp({
    mobile,
    templateName: process.env.MSG91_WA_CREDENTIALS_TEMPLATE || 'fwf_welcome_credentials',
    contentSid:   process.env.MSG91_WA_CREDENTIALS_SID   || '',
    variables: [
      name,
      userId,
      password,
      'https://www.fwfindia.org/member-login.html'
    ]
  });
}

/**
 * Send donation confirmation WhatsApp.
 * Template vars: {{1}}=name  {{2}}=amount  {{3}}=donationId  {{4}}=paymentId  {{5}}=date
 */
export async function sendWhatsAppDonation({ mobile, name, amount, donationId, paymentId }) {
  if (!mobile) return null;
  const formatted = Number(amount).toLocaleString('en-IN');
  const date      = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
  return _sendWhatsApp({
    mobile,
    templateName: process.env.MSG91_WA_DONATION_TEMPLATE || 'fwf_donation_confirmation',
    contentSid:   process.env.MSG91_WA_DONATION_SID   || '',
    variables: [name, `Rs. ${formatted}`, donationId, paymentId, date]
  });
}
