import mongoose from 'mongoose';

/**
 * PaymentLink — shareable link generated by a Member or Supporter
 *
 * When a donor/buyer pays through this link:
 *   • The creating member/supporter gets credited points
 *   • The payment is recorded in Donation or QuizTicket collection
 *
 * Link URL: https://www.fwfindia.org/pay/[link_id]
 */
const paymentLinkSchema = new mongoose.Schema({
  // Unique public ID embedded in the shareable URL
  link_id: {
    type: String,
    required: true,
    unique: true,
    index: true
  },

  // Who created the link
  created_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  member_id: { type: String, required: true },      // e.g. FWFM001
  member_name: { type: String, required: true },    // Display name for the pay page

  // Link purpose
  type: {
    type: String,
    enum: ['donation', 'quiz_ticket'],
    required: true
  },
  title: { type: String, default: '' },              // Optional custom message

  // Payment amount — null means donor/buyer chooses
  amount: { type: Number, default: null },

  // Running totals
  payment_count: { type: Number, default: 0 },
  total_collected: { type: Number, default: 0 },
  total_points_earned: { type: Number, default: 0 },

  active: { type: Boolean, default: true, index: true },

  created_at: { type: Date, default: Date.now }
}, {
  timestamps: { createdAt: 'created_at', updatedAt: false }
});

paymentLinkSchema.index({ created_by: 1, created_at: -1 });
paymentLinkSchema.index({ link_id: 1, active: 1 });

export default mongoose.model('PaymentLink', paymentLinkSchema);
